/*LAS REGLAS SON LAS SIGUIENTES:

1-MAYUSCULAS Y SIN ACENTOS:LAS PALABRAS SE ESCRIBIRAN EN MAYUSCULAS Y SIN ACENTOS
ejemplo   'QNEXT': 'QNED',


2-LETRAS A LA IZQUIERDA Y NUMEROS A LA DERECHA:SI SON NUMEROS LA VERSION DE CIFRA SE PONDRA A LA DERECHA Y LA LETRA A LA IZQUIERDA
ejemplo  'CINCUENTA Y CINCO': '55'


3-SUSTITUCION: SI DETECTA LA PALABRA DE LA IZQUIERDA LA SUSTITUYE POR LA DE LA  DERECHA  Y LA PONE EN EL BUSCADOR
ejemplo variable 'CINCUENTA':'50'  si digo Cincuenta al microfono me escribira 50


4-DETECCION DIRECTA: SI DETECTA LA PALABRA DE LA DERECHA, LA TOMA DIRECTAMENTE COMO BUENA Y LA PONE EN EL BUSCADOR
ejemplo variable 'CINCUENTA':'50'  si el microfono me detecta 50 me escribira 50


5-SOLO PALABRAS Y FRASES COMPLETAS: SI EN LA IZQUIERA PONEMOS UNA FRASE, A NO SER QUE LA ESCUCHE ENTERA NO LA ESCRIBIRA EN EL BUSCADOR
ejemplo variable  'CHURROS CON CHOCOLATE':'67', si digo churros no escribe nada, pero si digo churros con chocolate escribirá 67




*/
const palabrasclave = {

    'MI IDEA': 'MIDEA',
    'NI IDEA': 'MIDEA',
    'INFINITO': 'INFI',
    'INFINITON':'INFI',
    'HIGH SCHOOL': 'ICEC',
    'NEW POL': 'NEW',
    'LAVADORA': 'LAVADORA',
    'LAVADORAS': 'LAVADORA',
    'COMBIS':'COMB',
    'LAVAVAJILLAS': 'LAVAVAJILLAS',
    'COMBI': 'COMBI',
    'HORNO': 'HORNO',
    'LG': 'LG',
    'EJE': 'LG',
    'SAMSUNG': 'SAMSUNG',
    'HAIER':'HAIER',
    'JAVIER':'HAIER',
    'INDESIT':'INDESIT',
    'BOSCH':'BOS',
    'VOZ':'BOS',
    'CAMPANA':'CAMPANA',
    'SECADORA':'SECADORA',
    'CANDY':'CANDY',
    'ASPES':'ASPES',
    'CRISTAL':'CRISTAL',
    'BALAY':'BALAY',
    'INOXIDABLE':'INOX',
    'INOXIDABLES':'INOX',
    'BEKO':'BEKO',
    'SUPERIOR':'SUPERIOR',
    'WHIRLPOOL':'WHIRLPOOL',
    'INTEGRABLE':'INTEGRA',
    'INTEGRABLES':'INTEGRA',
    'CECOTEC':'CECOTEC',
    'NEGRO':'NEGR',
    'NEGRA':'NEGR',
    'MICROONDAS':'MICROONDAS',
    'PIROLITICO':'PIRO',
    'INDUCCION':'INDUC',
    'VITROCERAMICA':'VITRO',
    'INSTALACION':'INSTA',
    'LAVASECADORA':'LAVASEC',
    'CUARENTA Y CINCO':'45',
    '10 CUBIERTOS':'10',
    'DIEAZ CUBIERTOS':'10',
    'BRAND':'BRANDT',
    'SEIS KILOS':'6KG',
    '6 KILOS':'6KG',
    '6 KG':'6KG',
    'SIETE KILOS':'7KG',
    '7 KILOS':'7KG',
    '7 KG':'7KG',
    'OCHO KILOS':'8KG',
    '8 KILOS':'8KG',
    '8 KG':'8KG',
    'NUEVE KILOS':'9KG',
    '9 KILOS':'9KG',
    '9 KG':'9KG',
    'DIEZ KILOS':'10KG',
    '10 KILOS':'10KG',
    '10 KG':'10KG',
    'ONCE KILOS':'11KG',
    '11 KILOS':'11KG',
    '11 KG':'11KG',
    'SETENTA':'70',
    'HOOVER':'HOOVER',
    'ARISTON':'ARISTON',
    'MEPANSA':'MEPANSA',
    'CINCUENTA Y CINCO':'55',
    'MENORES DE 1,80':'17',
    'PEQUENOS DE 1,80':'17',
    'MAYORES DE 1,80':'18',
    'GRANDES DE 1,80':'18',
    'MAS DE DOS':'20',
    'MAS DE 2':'20',
    'PEQUENOS DE 2 METROS':'18',
    'PEQUENOS DE DOS METROS':'18',
    'PEQUENOS DE 2 M':'18',
    'PEQUENOS DE DOS M':'18',
    'GAS':'GAS',
    'BUTANO':'BUTANO',
    'PLACA':'PLACA',
    'SIDE':'BY',
    'SAID':'BY',
    'FRIGORIFICO':'FRIG',
    'AMERICANO':'AMER',
    'TOMA DE AGUA':'TOMA'











};